TEST_PARAMS = {
    'n_neighbors': 15,
    'n_epochs': 10,
    'random_state': 98765,
    'random_init': True,
    'umap_metric': False,
    'tsne_symmetrization': False,
    'optimize_method': 'gdr',
    'cython': False,
    'torch': False,
    'neg_sample_rate': 5,
    'normalized': False,
    'accelerated': False,
    'sym_attraction': False,
    'frobenius': False,
    'gpu': False,
    'num_threads': -1,
    'angular': False,
    'amplify_grads': False,
    'a': 1.5769434604,
    'b': 0.8950608780,
    'verbose': True
}
